stages:
    - prepare
    - test

image: centos:7.6.1810

variables:
    DOCKER_DRIVER: overlay2
    LANG: 'en_US.UTF-8'
    CONDA_VERSION: '4.5.4'
    
.prepare_environment:
   cache:
     key: ${CI_PIPELINE_ID}-wms
     untracked: true
   
   before_script:
     - yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm https://centos7.iuscommunity.org/ius-release.rpm
     - yum install -y curl bzip2 gcc bc python36u python36u-devel python36u-setuptools python36u-pip git
     - curl -LO https://repo.continuum.io/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh
     - bash Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh -b -p /usr/local/miniconda
     - export PATH=/usr/local/miniconda/bin:$PATH
     - conda update conda
     - conda install pip
     - if [[ ! -d lodseq ]]; then git clone https://github.com/CNRGH/LodSeq.git lodseq; fi
     - pushd lodseq/
     - curl -LO ftp://ftp.ncbi.nlm.nih.gov/hapmap/recombination/2011-01_phaseII_B37/genetic_map_HapMapII_GRCh37.tar.gz
     - mkdir -p data/inputs/genetic_map_HapMapII_GRCh37 
     - tar xf genetic_map_HapMapII_GRCh37.tar.gz -C data/inputs/genetic_map_HapMapII_GRCh37
     - popd

.test_genetic_data_with_snakemake: &test_genetic_data_with_snakemake
    stage: test 
    extends: .prepare_environment
    script:
        - pushd lodseq/
        - conda env create -n lodseq --file environment.yaml
        - snakemake_version=${CI_JOB_NAME/*-}
        - conda install -n lodseq -c conda-forge -c bioconda snakemake=${snakemake_version}=py36_0
        - source activate lodseq
        - mkdir test/
        - snakemake -v
        - snakemake --ignore-incomplete --reason --verbose --printshellcmds --timestamp  --configfile config.yaml
        - tar xf data/outputs/mergeResults.tar.gz -C data/outputs/
        - for f in $(ls test/mergeResults/results_*); do diff -q test/mergeResults/${f##*/} data/outputs/mergeResults/${f##*/}; done
        - popd

test_genetic_data_with_snakemake-4.8.0: *test_genetic_data_with_snakemake
